# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:3333/pixelsitedb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: POSTGRESQL
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO